# Generated by Django 5.2.4 on 2025-07-06 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiecastCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_info', models.TextField()),
                ('delivery_due_date', models.DateField()),
                ('status', models.CharField(choices=[('Purchased/Paid', 'Purchased/Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Overdue', 'Overdue')], default='Purchased/Paid', max_length=20)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('packaging_quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('product_quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diecast_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
