# Generated by Django 5.2.4 on 2025-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_diecastcar_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='scale',
            field=models.CharField(default='1:43', max_length=20),
        ),
    ]
