# Generated by Django 5.2.4 on 2025-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_diecastcar_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
