# Generated by Django 5.2.4 on 2025-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_diecastcar_facebook_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
