# Generated by Django 5.2.4 on 2025-07-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_diecastcar_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecastcar',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
