# Generated by Django 5.2.1 on 2025-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_diecastcar_remaining_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diecastcar',
            name='seller_name',
            field=models.CharField(default='Unknown Seller', max_length=200),
        ),
        migrations.AddField(
            model_name='diecastcar',
            name='website_url',
            field=models.URLField(blank=True, help_text='Facebook page, website URL or other website', max_length=500, null=True),
        ),
    ]
