# Generated by Django 5.2.4 on 2025-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_diecastcar_contact_mobile_diecastcar_seller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='delivery_service',
            field=models.CharField(blank=True, help_text='Delivery service provider name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diecastcar',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True),
        ),
    ]
