# Generated by Django 5.2.4 on 2025-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_diecastcar_delivery_service_diecastcar_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecastcar',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
