# Generated by Django 5.2.4 on 2025-07-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecastcar',
            name='status',
            field=models.CharField(choices=[('Purchased/Paid', 'Purchased/Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Overdue', 'Overdue'), ('Pre-Order', 'Pre-Order'), ('Commented Sold', 'Commented Sold')], default='Purchased/Paid', max_length=20),
        ),
    ]
