# Generated by Django 5.2.4 on 2025-07-23 05:47

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_diecastcar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcar',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of your model car', null=True, upload_to=inventory.models.car_image_upload_path),
        ),
    ]
