# Generated by Django 5.2.4 on 2025-08-08 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_diecastcar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMarketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ebay', 'eBay'), ('hobbydb', 'hobbyDB'), ('diecast_auction', 'Diecast Auction')], max_length=32)),
                ('external_id', models.CharField(help_text='Marketplace identifier (item ID, slug, etc.)', max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_links', to='inventory.diecastcar')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ebay', 'eBay'), ('hobbydb', 'hobbyDB'), ('diecast_auction', 'Diecast Auction')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_listing_url', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='inventory.diecastcar')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['car', 'marketplace', 'fetched_at'], name='inventory_m_car_id_563cc0_idx')],
            },
        ),
    ]
