# Generated by Django 5.2.4 on 2025-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_carmarketlink_marketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmarketlink',
            name='marketplace',
            field=models.CharField(choices=[('ebay', 'eBay'), ('hobbydb', 'hobbyDB'), ('diecast_auction', 'Diecast Auction'), ('facebook', 'Facebook'), ('web', 'Web Search')], max_length=32),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='marketplace',
            field=models.CharField(choices=[('ebay', 'eBay'), ('hobbydb', 'hobbyDB'), ('diecast_auction', 'Diecast Auction'), ('facebook', 'Facebook'), ('web', 'Web Search')], max_length=32),
        ),
    ]
