# Generated by Django 5.2.4 on 2025-09-19 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_carmarketlink_marketplace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFetchCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.IntegerField(default=0, help_text='Number of market fetches used today')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Date when credits were last reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_fetch_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Fetch Credit',
                'verbose_name_plural': 'Market Fetch Credits',
            },
        ),
    ]
