# Generated by Django 5.2.4 on 2025-10-05 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_overdue_alerts', models.BooleanField(default=True, help_text='Receive email alerts for overdue deliveries')),
                ('email_upcoming_alerts', models.BooleanField(default=True, help_text='Receive email alerts for upcoming deliveries (within 3 days)')),
                ('email_daily_summary', models.BooleanField(default=False, help_text='Receive daily email summary of delivery status')),
                ('alert_days_before_delivery', models.IntegerField(default=3, help_text='How many days before delivery to send upcoming alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
